#ifndef ZONAL_CONFIG_H
#define ZONAL_CONFIG_H

// System scale and zone definitions
#define TOTAL_SENSORS        100
#define NUM_ZONES            4

// Zone Mappings
#define ZONE_VISION          0  // 12 Sensors
#define ZONE_RADAR           1  // 20 Sensors
#define ZONE_PROXIMITY       2  // 24 Sensors
#define ZONE_VEHICLE_VITALS  3  // 44 Sensors

// Zone Connection Names (QNX Name Service)
#define ATTACH_ZONE_VISION   "adas_zone_vision"
#define ATTACH_ZONE_RADAR    "adas_zone_radar"
#define ATTACH_ZONE_PROX     "adas_zone_proximity"
#define ATTACH_ZONE_VITALS   "adas_zone_vitals"
#define ATTACH_CENTRAL       "adas_central_fusion"

// Sensor Categories
typedef enum {
    TYPE_SURROUND_CAM,
    TYPE_NIGHT_VISION,
    TYPE_LONG_RADAR,
    TYPE_SHORT_RADAR,
    TYPE_ULTRASONIC,
    TYPE_LIDAR,
    TYPE_IMU,
    TYPE_WHEEL_SPEED,
    TYPE_GNSS,
    TYPE_IMPACT_SENSOR
} SensorCategory_e;

typedef struct {
    int sensor_id;
    char name[20];
    SensorCategory_e category;
    int target_zone;
    int priority;
} sensor_config_t;

// HARDCODED DATABASE (100 Sensors)
static const sensor_config_t HARDCODED_FLEET[TOTAL_SENSORS] = {
    // [ZONE_VISION] 12 Sensors
    {0, "CAM_FRONT_C", TYPE_SURROUND_CAM, ZONE_VISION, 30},
    {1, "CAM_FRONT_L", TYPE_SURROUND_CAM, ZONE_VISION, 10},
    {2, "CAM_FRONT_R", TYPE_SURROUND_CAM, ZONE_VISION, 10},
    {3, "CAM_REAR_C",  TYPE_SURROUND_CAM, ZONE_VISION, 10},
    {4, "CAM_SIDE_L",  TYPE_SURROUND_CAM, ZONE_VISION, 5},
    {5, "CAM_SIDE_R",  TYPE_SURROUND_CAM, ZONE_VISION, 5},
    {6, "NV_THERMAL",  TYPE_NIGHT_VISION, ZONE_VISION, 15},
    {7, "CAM_ROOF",    TYPE_SURROUND_CAM, ZONE_VISION, 5},
    {8, "CAM_DMS",     TYPE_SURROUND_CAM, ZONE_VISION, 25},
    {9, "CAM_LANE_L",  TYPE_SURROUND_CAM, ZONE_VISION, 5},
    {10, "CAM_LANE_R", TYPE_SURROUND_CAM, ZONE_VISION, 5},
    {11, "CAM_PARK_F", TYPE_SURROUND_CAM, ZONE_VISION, 5},

    // [ZONE_RADAR] 20 Sensors
    {12, "RADAR_LR_F",  TYPE_LONG_RADAR, ZONE_RADAR, 50}, // High Priority
    {13, "RADAR_LR_R",  TYPE_LONG_RADAR, ZONE_RADAR, 30},
    {14, "RADAR_SR_FL", TYPE_SHORT_RADAR, ZONE_RADAR, 20},
    {15, "RADAR_SR_FR", TYPE_SHORT_RADAR, ZONE_RADAR, 20},
    {16, "RADAR_SR_RL", TYPE_SHORT_RADAR, ZONE_RADAR, 15},
    {17, "RADAR_SR_RR", TYPE_SHORT_RADAR, ZONE_RADAR, 15},
    {18, "RADAR_CRN_FL", TYPE_SHORT_RADAR, ZONE_RADAR, 10},
    {19, "RADAR_CRN_FR", TYPE_SHORT_RADAR, ZONE_RADAR, 10},
    {20, "RADAR_AUX_1", TYPE_SHORT_RADAR, ZONE_RADAR, 5}, {21, "RADAR_AUX_2", TYPE_SHORT_RADAR, ZONE_RADAR, 5},
    {22, "RADAR_AUX_3", TYPE_SHORT_RADAR, ZONE_RADAR, 5}, {23, "RADAR_AUX_4", TYPE_SHORT_RADAR, ZONE_RADAR, 5},
    {24, "RADAR_AUX_5", TYPE_SHORT_RADAR, ZONE_RADAR, 5}, {25, "RADAR_AUX_6", TYPE_SHORT_RADAR, ZONE_RADAR, 5},
    {26, "RADAR_AUX_7", TYPE_SHORT_RADAR, ZONE_RADAR, 5}, {27, "RADAR_AUX_8", TYPE_SHORT_RADAR, ZONE_RADAR, 5},
    {28, "RADAR_AUX_9", TYPE_SHORT_RADAR, ZONE_RADAR, 5}, {29, "RADAR_AUX_10", TYPE_SHORT_RADAR, ZONE_RADAR, 5},
    {30, "RADAR_AUX_11", TYPE_SHORT_RADAR, ZONE_RADAR, 5}, {31, "RADAR_AUX_12", TYPE_SHORT_RADAR, ZONE_RADAR, 5},

    // [ZONE_PROXIMITY] 24 Sensors
    {32, "LIDAR_FRONT", TYPE_LIDAR, ZONE_PROXIMITY, 60}, // Safety Critical
    {33, "LIDAR_REAR",  TYPE_LIDAR, ZONE_PROXIMITY, 40},
    {34, "LIDAR_LEFT",  TYPE_LIDAR, ZONE_PROXIMITY, 20},
    {35, "LIDAR_RIGHT", TYPE_LIDAR, ZONE_PROXIMITY, 20},
    {36, "USS_F_1", TYPE_ULTRASONIC, ZONE_PROXIMITY, 5}, {37, "USS_F_2", TYPE_ULTRASONIC, ZONE_PROXIMITY, 5},
    {38, "USS_F_3", TYPE_ULTRASONIC, ZONE_PROXIMITY, 5}, {39, "USS_F_4", TYPE_ULTRASONIC, ZONE_PROXIMITY, 5},
    {40, "USS_R_1", TYPE_ULTRASONIC, ZONE_PROXIMITY, 5}, {41, "USS_R_2", TYPE_ULTRASONIC, ZONE_PROXIMITY, 5},
    {42, "USS_R_3", TYPE_ULTRASONIC, ZONE_PROXIMITY, 5}, {43, "USS_R_4", TYPE_ULTRASONIC, ZONE_PROXIMITY, 5},
    {44, "USS_L_1", TYPE_ULTRASONIC, ZONE_PROXIMITY, 2}, {45, "USS_L_2", TYPE_ULTRASONIC, ZONE_PROXIMITY, 2},
    {46, "USS_L_3", TYPE_ULTRASONIC, ZONE_PROXIMITY, 2}, {47, "USS_L_4", TYPE_ULTRASONIC, ZONE_PROXIMITY, 2},
    {48, "USS_RR_1", TYPE_ULTRASONIC, ZONE_PROXIMITY, 2}, {49, "USS_RR_2", TYPE_ULTRASONIC, ZONE_PROXIMITY, 2},
    {50, "USS_RR_3", TYPE_ULTRASONIC, ZONE_PROXIMITY, 2}, {51, "USS_RR_4", TYPE_ULTRASONIC, ZONE_PROXIMITY, 2},
    {52, "LIDAR_AUX1", TYPE_LIDAR, ZONE_PROXIMITY, 10}, {53, "LIDAR_AUX2", TYPE_LIDAR, ZONE_PROXIMITY, 10},
    {54, "LIDAR_AUX3", TYPE_LIDAR, ZONE_PROXIMITY, 10}, {55, "LIDAR_AUX4", TYPE_LIDAR, ZONE_PROXIMITY, 10},

    // [ZONE_VEHICLE_VITALS] 44 Sensors
    {56, "IMU_CHASSIS", TYPE_IMU, ZONE_VEHICLE_VITALS, 70},
    {57, "GNSS_RTK",    TYPE_GNSS, ZONE_VEHICLE_VITALS, 10},
    {58, "WHEEL_FL",    TYPE_WHEEL_SPEED, ZONE_VEHICLE_VITALS, 20},
    {59, "WHEEL_FR",    TYPE_WHEEL_SPEED, ZONE_VEHICLE_VITALS, 20},
    {60, "WHEEL_RL",    TYPE_WHEEL_SPEED, ZONE_VEHICLE_VITALS, 20},
    {61, "WHEEL_RR",    TYPE_WHEEL_SPEED, ZONE_VEHICLE_VITALS, 20},
    {62, "STEERING_ABS", TYPE_IMU, ZONE_VEHICLE_VITALS, 30},
    {63, "BRAKE_PEDAL",  TYPE_IMU, ZONE_VEHICLE_VITALS, 40},
    {64, "GEAR_POS",     TYPE_IMU, ZONE_VEHICLE_VITALS, 10},
    {65, "ACCEL_PEDAL",  TYPE_IMU, ZONE_VEHICLE_VITALS, 15},
    // 66-99: Fill remaining with vitals
    {66, "TEMP_SOC", TYPE_IMU, ZONE_VEHICLE_VITALS, 5}, {67, "TEMP_BAT", TYPE_IMU, ZONE_VEHICLE_VITALS, 5},
    {68, "BMS_VOLT", TYPE_IMU, ZONE_VEHICLE_VITALS, 5}, {69, "BMS_CURR", TYPE_IMU, ZONE_VEHICLE_VITALS, 5},
    {70, "VIT_S1", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {71, "VIT_S2", TYPE_IMU, ZONE_VEHICLE_VITALS, 2},
    {72, "VIT_S3", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {73, "VIT_S4", TYPE_IMU, ZONE_VEHICLE_VITALS, 2},
    {74, "VIT_S5", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {75, "VIT_S6", TYPE_IMU, ZONE_VEHICLE_VITALS, 2},
    {76, "VIT_S7", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {77, "VIT_S8", TYPE_IMU, ZONE_VEHICLE_VITALS, 2},
    {78, "VIT_S9", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {79, "VIT_S10", TYPE_IMU, ZONE_VEHICLE_VITALS, 2},
    {80, "VIT_S11", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {81, "VIT_S12", TYPE_IMU, ZONE_VEHICLE_VITALS, 2},
    {82, "VIT_S13", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {83, "VIT_S14", TYPE_IMU, ZONE_VEHICLE_VITALS, 2},
    {84, "VIT_S15", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {85, "VIT_S16", TYPE_IMU, ZONE_VEHICLE_VITALS, 2},
    {86, "VIT_S17", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {87, "VIT_S18", TYPE_IMU, ZONE_VEHICLE_VITALS, 2},
    {88, "VIT_S19", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {89, "VIT_S20", TYPE_IMU, ZONE_VEHICLE_VITALS, 2},
    {90, "VIT_S21", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {91, "VIT_S22", TYPE_IMU, ZONE_VEHICLE_VITALS, 2},
    {92, "VIT_S23", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {93, "VIT_S24", TYPE_IMU, ZONE_VEHICLE_VITALS, 2},
    {94, "VIT_S25", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {95, "VIT_S26", TYPE_IMU, ZONE_VEHICLE_VITALS, 2},
    {96, "VIT_S27", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {97, "VIT_S28", TYPE_IMU, ZONE_VEHICLE_VITALS, 2},
    {98, "VIT_S29", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}, {99, "VIT_S30", TYPE_IMU, ZONE_VEHICLE_VITALS, 2}
};

#endif // ZONAL_CONFIG_H
